config/routes.rb
MyAlbum::Application.routes.draw do
  devise_for :users

  authenticated :user do 
    root :to => "albums#index"
  end

  resources :albums do
    resources :songs
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :cover, :name

  mount_uploader :cover, CoverUploader

  has_many :songs, :dependent => :destroy
  belongs_to :user

  validates :name, :presence => true
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :name, :song
  mount_uploader :song, SongUploader

  belongs_to :album

  validates :name, :song, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name

  has_many :albums, :dependent => :destroy
  has_many :songs, :through => :albums

  validates :name, :email, :presence => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_filter :get_album, :except => [ :index, :new ]

  def index
    @albums = Album.where(" name LIKE '%#{params[:search]}%'")
  end

  def new
    @album = Album.new
  end  

  def show
  end 

  def edit
  end 

  def update
    if @album.update_attributes params[:album]
      redirect_to album_path(@album)
    else
      render :action => :edit
    end  
  end  

  def destroy
    if @album.destroy
      flash[:notice] = 'Album removed successfully.'
    end  
    redirect_to albums_path
  end  

private
  def get_album
    @album = Album.find params[:id]
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/edit.html.erb
<%= form_for @album, { :multipart => true } do |f|%>
  Name <%= f.text_field :name %>
  Cover <%= f.file_field :cover %>
  <%= f.submit('Save') %>
<%end%>

app/views/albums/index.html.erb
<br />

<%= form_tag albums_path, :method => :get do %>
  Search - <%= text_field_tag :search, params[:search] %>
  <%= submit_tag('Search')%>
<% end %>

<table>
 <tr>
  <td>List of albums</td>
  <td></td>
  <td></td>
 </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <td><%= link_to album %></td>
    <td></td>
  </tr>
<% end %>

</table>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<%= form_for @album, { :multipart => true } do |f|%>
  Name <%= f.text_field :name %>
  Cover <%= f.file_field :cover %>
  <%= f.submit('Save') %>
<%end%>

app/views/albums/show.html.erb
<%= @album.name %>
<%= link_to 'Edit', edit_album_path(@album) %>
<%= link_to 'Remove', album_path(@album), :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyAlbum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] %>  
<% if current_user %>
  <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<% end %>

<%= yield %>

</body>
</html>